### ISSUE TITLE
training use API : Operation not permitted

### ISSUE THREAD

**Issue by wjljack** [regel/loudml#116]
I use docker to run loudml, in docker container bash, i can use cli to create model and train model, but when i use api , print log
```log
10.117.23.115 - - [2019-05-09 08:11:01] "GET /jobs/886743cd-70b3-49de-96d5-3af22649d7a4 HTTP/1.1" 200 263 0.000937
10.117.23.115 - - [2019-05-09 08:11:31] "POST /models/ping/_train?from=now-5d&to=now-3d HTTP/1.1" 200 147 0.003431
INFO:root:job[9eedf3bb-882c-4da1-9400-d565f05b2144] starting, nice=5
ERROR:root:job[9eedf3bb-882c-4da1-9400-d565f05b2144] failed: [Errno 1] Operation not permitted

```

**Comment by nonostar** [comment]
check the owner of the processus running loudmld, then set correct right to his data repository ...

**Comment by regel** [comment]
@wjljack I noticed that it's been a little while since we last heard from you, and I wanted to check in to remind you about this ticket. Can we close this ticket? You can always respond to the ticket to reopen it if needed.

@nonostar is correct. Loud ML installs a local user and group (loudml:loudml) and the loudmld daemon should run as this unprivileged user. This also means the files in `/var/lib/loudml` must belong to the `loudml` group.

If you are using the CLI, you will need to add your local user to secondary group `loudml`, then logout from your Linux session, and log in again.

You can find a note in the documentation: https://loudml.io/en/loudml/reference/current/cli.html
