### ISSUE TITLE
binary 'loudml' is missing from docker container

### ISSUE THREAD

**Issue by camAtGitHub** [regel/loudml#152]
In the current docker image: "loudml/loudml:latest-devel" - I think the binary 'loudml' is missing
'loudmld' is there, but not 'loudml'

**Comment by regel** [comment]
Good day Cam!

This is intentional. A refactoring is in progress. We now split the server code and client code. You should see the changes in getting started documentation.

The CLI moved to PyPI. Search ‘loudml-python’ on PyPI and readthedocs for more info. So the client can now connect to a remote Loud ML « node » (or cluster).

Meanwhile, we also package other client libraries for JavaScript and Go to facilitate the integration with other apps and increase our test coverage. Work in progress.

**Comment by camAtGitHub** [comment]
Ok Then!
I'm eagerly awaiting the updated doco :-) 
Maybe even lucene query language for Elastic ;-) 
Thanks
