### ISSUE TITLE
LoudML usage

### ISSUE THREAD

**Issue by sve71** [regel/loudml#207]
Hi everyone! Hope you are all doing well.

Could you help me, please, with the questions below?

- How are values scored to set alerts?
- Is it possible to control metrics only for the current time of day? For example, I’d like to monitor and send alerts only if an anomaly happens at night.
- Are there the best practices for preparing and training models in LoudML? For example, how to take seasonality into account?

By the way, is there anyone who uses TICK-L stack in VoIP? In what cases is it possible to apply the stack except alerting?

Thanks in advance!

**Comment by sve71** [comment]
Hello there,

Any comments? If it's the wrong place, tell me, please, where I can ask the questions.

Thx a lot:)

**Comment by regel** [comment]
Hello. I noticed the questions but some may be out of scope for Github issues. 

Loud ML is first designed to make ML easier to use and more accessible. One first model supported is specialized for anomaly detection use-cases. However, we aim for a larger audience and new ML model implementations can be added (eg. add your own) and contributed in order to open new verticals and new applications. Refer to `CONTRIBUTING.md` and the code of conduct for more information. Loud ML is free software and I invite everyone to contribute.
