### ISSUE TITLE
Ability to add/delete datasources using REST

### ISSUE THREAD

**Issue by daradermody** [regel/loudml#44]
Currently, datasources can only be added using the config file before startup. This is a request for the ability to add new datasources via REST without having to restart the application.

My use case is when creating new indices in Elasticsearch, I don't want to have to go the server hosting LoudML to add it.

**Comment by regel** [comment]
@daradermody, Hi Dara, I guess it would be add and delete operations, right? We will probably need JWT tokens on top to authenticate the request. What do you think?

**Comment by daradermody** [comment]
Hey @regel, yes, this would only consist of add and delete operations (update would be nice, but isn't particularly necessary).

If you were to add authentication, I'd think it would then have to be applied to all interfaces (especially `_train` and `_start` as these would send data to Elasitcsearch). For our use case, though, we wouldn't use authentication on Loud ML because queries from our UI will be routed through our own server which already has an authentication service.

**Comment by vnyb** [comment]
Hi @daradermody,

This new feature would indeed bring more flexibility, that's why it will be added to the next LoudML version.

Meanwhile, you can use an index pattern (e.g. `index-*`) instead of an index name. In this way, you will be able to query several indexes. However, this can lead to more costly requests because Elasticsearch will search all the indexes matching the pattern. But, depending on your use case, this may be a temporary solution for you.

**Comment by daradermody** [comment]
@vnyb Great, thanks for the feedback! :smiley:

**Comment by regel** [comment]
- [ ] Add and delete data sources using new REST endpoints
- [ ] Define optional JWT tokens to apply to all endpoints in the API

**Comment by regel** [comment]
@daradermody feel free to contribute and submit a pull request, 1.5 is released in OSS.
