### ISSUE TITLE
Question: Are models upgraded?

### ISSUE THREAD

**Issue by daradermody** [regel/loudml#75]
Does Loud ML do any upgrade procedure on models? For example, with the release of 1.4.3, the following format is deprecated:
```
"features": {
    "io": [
       {... feature ...},
       {... feature ...},
       ...
    ],
    "i": [...],
    "o": [...]
}
```
Are existing models that are in `/var/lib/loudml` automatically transformed to the newer format, or will they have to be deleted and recreated again?

**Comment by regel** [comment]
The old format can still be used while creating new models, although internally they will be converted to the new format (list) when serialised to JSON.

**Comment by daradermody** [comment]
Speaking more generally, is this a long term plan, that API changes will support legacy indefinitely (i.e. of the entire API, not just model creation)? Since you've marked the format as deprecated, it sounded like it will be removed at some point in the future.

**Comment by regel** [comment]
Hi Dara,

The ideal scenario is a seamless migration, and deprecated means we will drop the old format. I don't know when. We're trying to avoid breaking changes, as much as possible, but sometimes they are required and we want to document them in the release notes.

We're missing something in the data store, since previous settings.json files can still be written to disk using the old format and are not (yet) automatically converted to the latest format - is it your point?

**Comment by daradermody** [comment]
Hey Sebastien, that clarifies it a bit more for me, thanks. When you do define the length of a deprecation period, it would be good to document that.
